### PR TITLE
Check for deallocation in `message_from_boxed_slice` test

### PR DESCRIPTION
**Pull request by kalcutter**

### CODE REVIEW

**Comment by kalcutter** [comment]
This is a trivial improvement to the test. Please merge.

**Comment by kalcutter** [comment]
@Jasper-Bekkers Please consider this trivial change that improves a test. The test asserts that the deallocation has the correct layout. This PR also makes sure that the deallocation actually happens.

**Comment by Jasper-Bekkers** [comment]
Will do, could you elaborate a bit more on why this change is needed, i have very little context for this test. Code looks simple enough to just merge in though.

**Comment by kalcutter** [comment]
I am the original author of this test. You can find the relevant PR here: https://github.com/erickt/rust-zmq/pull/301

After it was merged, I realized the test would have been slightly better with this added assert so I made this PR.

**Pull request merged**
