### PR TITLE
Added rtdealer and fileio3 examples

### PR DESCRIPTION
**Pull request by dginev**
Modelled after: http://zguide.zeromq.org/c:rtdealer

Probably needs code review, but it seems fully operational to me. Feedback welcome, will be happy to improve it.

### CODE REVIEW

**Comment by dginev** [comment]
I also added the fileio3 example, which can also benefit from a code review. But it works as expected, as I understand it.

**Comment by erickt** [comment]
A belated thank you! This looks good to me but needs a rebase.

**Comment by dginev** [comment]
OK, rebased and updated to using std::time and the new tempfile API.

It seems the CI testers fail, but for unrelated reasons to my changes:
> /home/travis/build/erickt/rust-zmq/target/debug/compile_tests-cd33b1aafa32176a: error while loading shared libraries: libtest-411f48d3.so: cannot open shared object file: No such file or directory
error: test failed

The stable and beta build on Travis pass though, so this PR is likely safe. Let me know if you'd like any changes.

**Comment by rotty** [comment]
I've now taken the liberty to integrate your pull request as commit 133e7e3, as I didn't want to have you go through yet another rebase cycle. I hope that's ok.

**Comment by dginev** [comment]
Naturally, happy to see the examples merged. Thanks!

**Pull request closed without merging**
