### PR TITLE
Add additional socket configuration functions

### PR DESCRIPTION
**Pull request by reset**
* Add option for send and recieve timeouts
* Add option for router mandatory
* Add option for probe router

### CODE REVIEW

**Comment by erickt** [comment]
A belated thanks (and an appeal to help maintain this crate if you're interested)!

**Comment by reset** [comment]
@erickt I'd love to, we're currently using this in a project called [Habitat](http://habitat.sh). Thanks so much for doing all this groundwork!

**Comment by erickt** [comment]
Habitat is really neat! I've been wanting to play with it for a while.

Thanks so much for your offer to help. I haven't had time to play with zeromq for quite some time, and unfortunately the other people who were helping out have moved on to other things. I'll give you commit to the repo. I'd appreciate any help reviewing patches and fixing bugs. 

Also, if you need to reach me directly you can alwayd reach me as "erickt" on irc.mozilla.org.

**Comment by reset** [comment]
@erickt appreciate the commit bit, I'll help out with reviewing issues/prs for sure

**Pull request merged**
