### PR TITLE
Add ZMQ_STREAM socket type #95

### PR DESCRIPTION
**Pull request by karec**
Adding ZMQ_STREAM socket type + example and tests

### CODE REVIEW

**Comment by rotty** [comment]
Looks good! A few cosmetic "issues":

- Please put the issue reference into the commit message body; this way the subject is not cluttered and does read better (sorry, I tend to be overly picky about commit messages).
- If changes are interdependent, please put them into one commit, by rebasing/amending and force-pushing. This makes things much easier to review.

And for something more meaty: could you extend the test to use two threads, and bind the socket to an ephemeral[1]  port on the loopback address? You could use `tests/shared-context.rs` as an example. The idea here is to introduce as little dependencies and effect on the state of the system running the tests, which is why the loopback address is better than the wildcard address, and an ephemeral port preferable to a fixed port, which might already be in use.

[1] I just noticed that binding on an ephemeral port is not feasible without adding support for the `ZMQ_LAST_ENDPOINT` socket option, so ignore that part if you don't feel motivated to fill in that part of the API as well. Note that this should be a separate change, whether as a precursor pull request or after merging this pull request.

Thanks for putting up with my pedantry ;-).

**Comment by rotty** [comment]
I've now opened issue #110 regarding `ZMQ_LAST_ENDPOINT`. Unless I happen to fix that before you come around to revisiting this pull request, ignore the part about ephemeral ports -- the point about binding to the loopback address still holds, though.

**Comment by karec** [comment]
Sorry for the lack of news, busy week. I will try to work on it this weekend to improve the PR following your recommendations

**Comment by rotty** [comment]
Is merged into master in slightly tweaked form now.

**Pull request closed without merging**
