### PR TITLE
implement AsRawFd

### LINKED ISSUE #305: Implement AsRawFd/AsRawSocket for Socket
So we can take advantage of [smol::Async](https://github.com/stjepang/smol/blob/master/src/async_io.rs#L107) directly.

### PR DESCRIPTION
**Pull request by yihuang**
Fix #305

### CODE REVIEW

**Comment by peterjoel** [comment]
@yihuang  You might also be interested contributing to https://github.com/wusyong/async-zmq 
It is based on this crate as dependency.

**Comment by yihuang** [comment]
> @yihuang You might also be interested contributing to https://github.com/wusyong/async-zmq
> It is based on this crate as dependency.

That library don't look optimal for me:
- much more code than the async example I provided
- spawn it's own [reactor thread](https://github.com/wusyong/async-zmq/blob/master/src/reactor/watcher.rs#L134), rather than allow user to provide reactor/runtime.
- don't work on windows because of [mio::EventedFd](https://github.com/wusyong/async-zmq/blob/master/src/reactor/evented.rs#L3)

**Comment by kalcutter** [comment]
Can you separate the `AsRawFd` impls and example into separate PRs? I imagine there would be no issue getting the `AsRawFd` change merged.

**Comment by yihuang** [comment]
> Can you separate the `AsRawFd` impls and example into separate PRs? I imagine there would be no issue getting the `AsRawFd` change merged.

Done, removed the example from this PR, add made another one.

**Comment by erickt** [comment]
thanks! I'm not crazy about the unwraps here, but there's not much we can do if `AsRawFd()` doesn't let us return a Result.

**Comment by kalcutter** [comment]
Another possibility is to return -1 for the fd. Maybe there is already a precedence for this?

**Pull request merged**
