### PR TITLE
Changes for rust 1.0.0-alpha2

### PR DESCRIPTION
**Pull request by jedisct1**

### CODE REVIEW

**Comment by erickt** [comment]
Thanks!

**Comment by erickt** [comment]
@jedisct1: You've been using zmq much more frequently than I recently. Interested in having commit/push access to crates.io?

**Comment by jedisct1** [comment]
Sad to hear that you're not using zmq much any more.
But I'd be glad to keep maintaining the crate if you like.

**Comment by erickt** [comment]
@jedisct1: It's hopefully just a short diversion. I'm trying to get my serialization stuff ready for 1.0. I gave you commit access to the repo. Can you also create an account and login on https://crates.io? I'll add you to the release owners there too.

**Comment by jedisct1** [comment]
I use my Github account to login on crates.io. Do I need to create a distinct account?

**Comment by erickt** [comment]
@jedisct1: problem was on my side. You're now co-owner of the zmq-sys and zmq crates :)

**Pull request merged**
